import { Question, Team } from './types';

export const DEMO_TEAMS: Team[] = [
  { team_id: 'TEAM01', team_number: 1, team_name: 'Đội 01', display_name: 'Đội 01 - Rồng Vàng', status: 'ACTIVE', connected: false, avatar_color: '#3B82F6', created_at: new Date().toISOString() },
  { team_id: 'TEAM02', team_number: 2, team_name: 'Đội 02', display_name: 'Đội 02 - Phượng Hoàng', status: 'ACTIVE', connected: false, avatar_color: '#EF4444', created_at: new Date().toISOString() },
  { team_id: 'TEAM03', team_number: 3, team_name: 'Đội 03', display_name: 'Đội 03 - Kỳ Lân', status: 'ACTIVE', connected: false, avatar_color: '#10B981', created_at: new Date().toISOString() },
  { team_id: 'TEAM04', team_number: 4, team_name: 'Đội 04', display_name: 'Đội 04 - Bạch Hổ', status: 'ACTIVE', connected: false, avatar_color: '#F59E0B', created_at: new Date().toISOString() },
  { team_id: 'TEAM05', team_number: 5, team_name: 'Đội 05', display_name: 'Đội 05 - Tia Chớp', status: 'ACTIVE', connected: false, avatar_color: '#8B5CF6', created_at: new Date().toISOString() },
  { team_id: 'TEAM06', team_number: 6, team_name: 'Đội 06', display_name: 'Đội 06 - Ngọn Lửa', status: 'ACTIVE', connected: false, avatar_color: '#EC4899', created_at: new Date().toISOString() },
  { team_id: 'TEAM07', team_number: 7, team_name: 'Đội 07', display_name: 'Đội 07 - Bão Táp', status: 'ACTIVE', connected: false, avatar_color: '#06B6D4', created_at: new Date().toISOString() },
  { team_id: 'TEAM08', team_number: 8, team_name: 'Đội 08', display_name: 'Đội 08 - Đỉnh Cao', status: 'ACTIVE', connected: false, avatar_color: '#84CC16', created_at: new Date().toISOString() },
  { team_id: 'TEAM09', team_number: 9, team_name: 'Đội 09', display_name: 'Đội 09 - Sao Băng', status: 'ACTIVE', connected: false, avatar_color: '#F97316', created_at: new Date().toISOString() },
  { team_id: 'TEAM10', team_number: 10, team_name: 'Đội 10', display_name: 'Đội 10 - Kim Cương', status: 'ACTIVE', connected: false, avatar_color: '#6366F1', created_at: new Date().toISOString() },
  { team_id: 'TEAM11', team_number: 11, team_name: 'Đội 11', display_name: 'Đội 11 - Thần Tốc', status: 'ACTIVE', connected: false, avatar_color: '#14B8A6', created_at: new Date().toISOString() },
  { team_id: 'TEAM12', team_number: 12, team_name: 'Đội 12', display_name: 'Đội 12 - Trí Tuệ', status: 'ACTIVE', connected: false, avatar_color: '#D946EF', created_at: new Date().toISOString() },
  { team_id: 'TEAM13', team_number: 13, team_name: 'Đội 13', display_name: 'Đội 13 - Đại Bàng', status: 'ACTIVE', connected: false, avatar_color: '#EAB308', created_at: new Date().toISOString() },
  { team_id: 'TEAM14', team_number: 14, team_name: 'Đội 14', display_name: 'Đội 14 - Chiến Binh', status: 'ACTIVE', connected: false, avatar_color: '#64748B', created_at: new Date().toISOString() },
  { team_id: 'TEAM15', team_number: 15, team_name: 'Đội 15', display_name: 'Đội 15 - Tiên Phong', status: 'ACTIVE', connected: false, avatar_color: '#0EA5E9', created_at: new Date().toISOString() },
  { team_id: 'TEAM16', team_number: 16, team_name: 'Đội 16', display_name: 'Đội 16 - Bất Bại', status: 'ACTIVE', connected: false, avatar_color: '#22C55E', created_at: new Date().toISOString() },
  { team_id: 'TEAM17', team_number: 17, team_name: 'Đội 17', display_name: 'Đội 17 - Vô Địch', status: 'ACTIVE', connected: false, avatar_color: '#A855F7', created_at: new Date().toISOString() },
  { team_id: 'TEAM18', team_number: 18, team_name: 'Đội 18', display_name: 'Đội 18 - Khát Vọng', status: 'ACTIVE', connected: false, avatar_color: '#F43F5E', created_at: new Date().toISOString() },
  { team_id: 'TEAM19', team_number: 19, team_name: 'Đội 19', display_name: 'Đội 19 - Sáng Tạo', status: 'ACTIVE', connected: false, avatar_color: '#38BDF8', created_at: new Date().toISOString() },
  { team_id: 'TEAM20', team_number: 20, team_name: 'Đội 20', display_name: 'Đội 20 - Tinh Hoa', status: 'ACTIVE', connected: false, avatar_color: '#FB923C', created_at: new Date().toISOString() },
];

export const DEMO_QUESTIONS: Question[] = [
  {
    id: 'Q01',
    question_number: 1,
    content: 'Mô hình OSI (Open Systems Interconnection) gồm có bao nhiêu tầng?',
    option_a: '4 tầng',
    option_b: '5 tầng',
    option_c: '7 tầng',
    option_d: '8 tầng',
    correct_answer: 'C',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Mô hình OSI gồm 7 tầng: Vật lý, Liên kết dữ liệu, Mạng, Giao vận, Phiên, Trình diễn, Ứng dụng.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q02',
    question_number: 2,
    content: 'Giao thức nào hoạt động ở tầng Giao vận (Transport Layer) và cung cấp dịch vụ truyền dữ liệu tin cậy (reliable)?',
    option_a: 'UDP',
    option_b: 'TCP',
    option_c: 'IP',
    option_d: 'ICMP',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'TCP (Transmission Control Protocol) là giao thức hướng kết nối và đảm bảo độ tin cậy.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q03',
    question_number: 3,
    content: 'Cấu trúc dữ liệu nào hoạt động theo nguyên tắc LIFO (Last In First Out)?',
    option_a: 'Queue (Hàng đợi)',
    option_b: 'Stack (Ngăn xếp)',
    option_c: 'Linked List (Danh sách liên kết)',
    option_d: 'Binary Tree (Cây nhị phân)',
    correct_answer: 'B',
    points: 0.6,
    category: 'Cấu trúc dữ liệu',
    explanation: 'Ngăn xếp (Stack) đưa phần tử vào sau cùng và lấy ra đầu tiên (LIFO).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q04',
    question_number: 4,
    content: 'Trong hệ điều hành Linux, lệnh nào được dùng để kiểm tra địa chỉ IP của các card mạng?',
    option_a: 'ip a hoặc ifconfig',
    option_b: 'ping -a',
    option_c: 'netstat -l',
    option_d: 'traceroute',
    correct_answer: 'A',
    points: 0.6,
    category: 'Hệ điều hành',
    explanation: 'Lệnh `ip a` (hoặc `ip addr`, `ifconfig`) dùng để hiển thị cấu hình mạng và địa chỉ IP.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q05',
    question_number: 5,
    content: 'Thuật toán mã hóa bất đối xứng nào được sử dụng rộng rãi trong chữ ký số và trao đổi khóa?',
    option_a: 'AES-256',
    option_b: 'DES',
    option_c: 'RSA',
    option_d: 'RC4',
    correct_answer: 'C',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'RSA là thuật toán mã hóa khóa công khai (bất đối xứng) nổi tiếng nhất thế giới.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q06',
    question_number: 6,
    content: 'Cổng (Port) mặc định của giao thức HTTPS là gì?',
    option_a: '80',
    option_b: '443',
    option_c: '8080',
    option_d: '22',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Port chuẩn của HTTPS là 443, trong khi HTTP là 80, SSH là 22.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q07',
    question_number: 7,
    content: 'Độ phức tạp thời gian trung bình (Average Time Complexity) của thuật toán sắp xếp QuickSort là gì?',
    option_a: 'O(N)',
    option_b: 'O(N log N)',
    option_c: 'O(N^2)',
    option_d: 'O(log N)',
    correct_answer: 'B',
    points: 0.6,
    category: 'Thuật toán',
    explanation: 'QuickSort có độ phức tạp trung bình là O(N log N).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q08',
    question_number: 8,
    content: 'Trong cơ sở dữ liệu quan hệ, từ khóa nào dùng để kết hợp kết quả từ hai bảng theo điều kiện?',
    option_a: 'UNION',
    option_b: 'JOIN',
    option_c: 'GROUP BY',
    option_d: 'ORDER BY',
    correct_answer: 'B',
    points: 0.6,
    category: 'Cơ sở dữ liệu',
    explanation: 'Từ khóa `JOIN` (INNER JOIN, LEFT JOIN, ...) được sử dụng để kết hợp dữ liệu giữa các bảng.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q09',
    question_number: 9,
    content: 'Loại tấn công mạng nào làm tràn ngập lưu lượng máy chủ khiến dịch vụ bị gián đoạn đối với người dùng hợp lệ?',
    option_a: 'Phishing',
    option_b: 'DDoS (Distributed Denial of Service)',
    option_c: 'SQL Injection',
    option_d: 'Man-in-the-Middle',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'Tấn công từ chối dịch vụ phân tán (DDoS) gây nghẽn băng thông và tài nguyên máy chủ.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q10',
    question_number: 10,
    content: 'Trong kiến trúc máy tính, bộ nhớ nào có tốc độ truy xuất nhanh nhất đối với CPU?',
    option_a: 'RAM',
    option_b: 'Ổ cứng SSD NVMe',
    option_c: 'Bộ nhớ Cache (L1, L2, L3) và Registers',
    option_d: 'ROM BIOS',
    correct_answer: 'C',
    points: 0.6,
    category: 'Kiến trúc máy tính',
    explanation: 'Thanh ghi (Registers) và bộ nhớ đệm Cache nằm ngay trong CPU có tốc độ nhanh nhất.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q11',
    question_number: 11,
    content: 'Trong lập trình hướng đối tượng (OOP), tính chất nào cho phép một lớp con kế thừa thuộc tính và phương thức từ lớp cha?',
    option_a: 'Encapsulation (Đóng gói)',
    option_b: 'Inheritance (Kế thừa)',
    option_c: 'Polymorphism (Đa hình)',
    option_d: 'Abstraction (Trừu tượng)',
    correct_answer: 'B',
    points: 0.6,
    category: 'Lập trình',
    explanation: 'Tính kế thừa (Inheritance) cho phép tái sử dụng mã nguồn và mở rộng từ lớp cơ sở.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q12',
    question_number: 12,
    content: 'Địa chỉ IPv4 có độ dài bao nhiêu bit?',
    option_a: '16 bit',
    option_b: '32 bit',
    option_c: '64 bit',
    option_d: '128 bit',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'IPv4 dài 32 bit (4 byte), trong khi IPv6 dài 128 bit.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q13',
    question_number: 13,
    content: 'Công cụ quản lý phiên bản mã nguồn (Version Control System) phân tán phổ biến nhất hiện nay là gì?',
    option_a: 'SVN',
    option_b: 'Git',
    option_c: 'CVS',
    option_d: 'Mercurial',
    correct_answer: 'B',
    points: 0.6,
    category: 'Kỹ thuật phần mềm',
    explanation: 'Git được Linus Torvalds tạo ra vào năm 2005 và là hệ thống VCS chuẩn mực toàn cầu.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q14',
    question_number: 14,
    content: 'Thuật toán tìm kiếm nhị phân (Binary Search) yêu cầu mảng đầu vào phải thỏa mãn điều kiện gì?',
    option_a: 'Mảng phải có độ dài là số chẵn',
    option_b: 'Mảng phải được sắp xếp trước theo thứ tự',
    option_c: 'Mảng chỉ chứa số nguyên dương',
    option_d: 'Mảng không được chứa giá trị 0',
    correct_answer: 'B',
    points: 0.6,
    category: 'Thuật toán',
    explanation: 'Binary Search chỉ áp dụng được trên tập dữ liệu đã sắp xếp (Sorted array).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q15',
    question_number: 15,
    content: 'Kỹ thuật ảo hóa containerization (ví dụ Docker) khác với máy ảo truyền thống (VM) ở điểm cốt lõi nào?',
    option_a: 'Container không chạy được ứng dụng Web',
    option_b: 'Container dùng chung nhân hệ điều hành (Shared Host Kernel) giúp nhẹ và khởi động tức thì',
    option_c: 'Container yêu cầu cài đặt Hypervisor Type 1',
    option_d: 'Container không có hệ thống tệp tin riêng',
    correct_answer: 'B',
    points: 0.6,
    category: 'Điện toán đám mây',
    explanation: 'Docker Container chia sẻ kernel của host OS, không cần guest OS đầy đủ như VM.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q16',
    question_number: 16,
    content: 'Định dạng dữ liệu nào dựa trên văn bản nhẹ, thường được dùng để trao đổi dữ liệu giữa máy chủ và trình duyệt web?',
    option_a: 'JSON (JavaScript Object Notation)',
    option_b: 'Binary RAW',
    option_c: 'BSON Native',
    option_d: 'Protobuf v1',
    correct_answer: 'A',
    points: 0.6,
    category: 'Công nghệ thông tin',
    explanation: 'JSON là chuẩn định dạng trao đổi dữ liệu dạng văn bản phổ biến nhất thế giới.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q17',
    question_number: 17,
    content: 'Khái niệm "Deadlock" trong hệ điều hành xảy ra khi nào?',
    option_a: 'Khi CPU bị quá nhiệt và tự tắt',
    option_b: 'Khi hai hoặc nhiều tiến trình cùng chờ đợi tài nguyên mà tiến trình khác đang giữ vĩnh viễn',
    option_c: 'Khi bộ nhớ RAM bị đầy 100%',
    option_d: 'Khi đường truyền Internet bị ngắt kết nối',
    correct_answer: 'B',
    points: 0.6,
    category: 'Hệ điều hành',
    explanation: 'Deadlock (bế tắc) là tình trạng các tiến trình giữ tài nguyên và cùng chờ đợi lẫn nhau.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q18',
    question_number: 18,
    content: 'Hàm băm một chiều (Hash Function) an toàn chuẩn NIST có đặc điểm nào?',
    option_a: 'Có thể dễ dàng giải mã ngược lại chuỗi ban đầu',
    option_b: 'Cùng một dữ liệu đầu vào luôn cho ra cùng một chuỗi băm có độ dài cố định',
    option_c: 'Độ dài chuỗi băm luôn thay đổi theo kích thước file',
    option_d: 'Không chống được va chạm (collision)',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'Hàm băm (SHA-256, SHA-3) luôn tạo ra chuỗi đầu ra độ dài cố định và tính toán một chiều.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q19',
    question_number: 19,
    content: 'Tường lửa (Firewall) trạng thái (Stateful Inspection) lọc gói tin dựa trên yếu tố nào?',
    option_a: 'Chỉ dựa trên địa chỉ MAC nguồn',
    option_b: 'Theo dõi trạng thái của các kết nối mạng đang hoạt động cùng với IP và Port',
    option_c: 'Chỉ kiểm tra định dạng tên file đính kèm',
    option_d: 'Chỉ chặn email rác',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'Stateful firewall theo dõi bảng trạng thái kết nối (Connection State Table) để ra quyết định.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q20',
    question_number: 20,
    content: 'Kiến trúc mạng nơ-ron Transformer ra mắt năm 2017 sử dụng cơ chế đột phá nào?',
    option_a: 'Self-Attention Mechanism',
    option_b: 'Convolution Pooling',
    option_c: 'Markov Decision Process',
    option_d: 'Recurrent Feedback Loop',
    correct_answer: 'A',
    points: 0.6,
    category: 'Trí tuệ nhân tạo',
    explanation: 'Bài báo "Attention Is All You Need" của Google giới thiệu cơ chế Self-Attention làm nền tảng cho LLM.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q21',
    question_number: 21,
    content: 'Dải địa chỉ IP riêng (Private IP) theo chuẩn RFC 1918 dành cho lớp C (Class C) là gì?',
    option_a: '10.0.0.0 đến 10.255.255.255',
    option_b: '172.16.0.0 đến 172.31.255.255',
    option_c: '192.168.0.0 đến 192.168.255.255',
    option_d: '127.0.0.0 đến 127.255.255.255',
    correct_answer: 'C',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Dải IP Private lớp C là 192.168.0.0/16, rất phổ biến trong mạng LAN.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q22',
    question_number: 22,
    content: 'Hệ quản trị cơ sở dữ liệu quan hệ mã nguồn mở nào sử dụng ngôn ngữ truy vấn SQL và logo hình con cá heo?',
    option_a: 'PostgreSQL',
    option_b: 'MySQL',
    option_c: 'MongoDB',
    option_d: 'Redis',
    correct_answer: 'B',
    points: 0.6,
    category: 'Cơ sở dữ liệu',
    explanation: 'MySQL có linh vật là chú cá heo tên Sakila.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q23',
    question_number: 23,
    content: 'Giao thức nào được sử dụng để phân giải tên miền (ví dụ google.com) thành địa chỉ IP?',
    option_a: 'DHCP',
    option_b: 'DNS (Domain Name System)',
    option_c: 'ARP',
    option_d: 'SNMP',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'DNS chuyển đổi tên miền dễ nhớ thành địa chỉ IP dạng số mà máy tính hiểu được.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q24',
    question_number: 24,
    content: 'Trong ngôn ngữ lập trình C/C++, con trỏ (pointer) là biến dùng để lưu trữ cái gì?',
    option_a: 'Giá trị số nguyên lớn',
    option_b: 'Địa chỉ ô nhớ của một biến khác',
    option_c: 'Tên của hàm thực thi',
    option_d: 'Kích thước của tập tin',
    correct_answer: 'B',
    points: 0.6,
    category: 'Lập trình',
    explanation: 'Con trỏ trong C/C++ lưu địa chỉ vùng nhớ RAM trỏ tới biến đích.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q25',
    question_number: 25,
    content: 'Loại tấn công chèn mã lệnh độc hại vào cơ sở dữ liệu thông qua các trường nhập liệu trên website được gọi là gì?',
    option_a: 'Cross-Site Scripting (XSS)',
    option_b: 'SQL Injection (SQLi)',
    option_c: 'Buffer Overflow',
    option_d: 'DNS Spoofing',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'SQL Injection lợi dụng lỗ hổng không kiểm tra dữ liệu đầu vào để thực thi truy vấn trái phép.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q26',
    question_number: 26,
    content: 'Đơn vị đo lường cơ bản nhỏ nhất của thông tin trong máy tính là gì?',
    option_a: 'Byte',
    option_b: 'Bit (Binary Digit)',
    option_c: 'Nibble',
    option_d: 'Word',
    correct_answer: 'B',
    points: 0.6,
    category: 'Khoa học máy tính',
    explanation: 'Bit là đơn vị nhỏ nhất, nhận 1 trong 2 giá trị 0 hoặc 1. 1 Byte = 8 Bit.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q27',
    question_number: 27,
    content: 'Chuẩn mã hóa ký tự nào hỗ trợ hiển thị hầu hết tất cả các ngôn ngữ chữ viết trên thế giới, bao gồm cả tiếng Việt có dấu?',
    option_a: 'ASCII',
    option_b: 'Unicode (UTF-8 / UTF-16)',
    option_c: 'EBCDIC',
    option_d: 'ISO-8859-1',
    correct_answer: 'B',
    points: 0.6,
    category: 'Khoa học máy tính',
    explanation: 'Unicode là tiêu chuẩn công nghiệp mã hóa văn bản đa ngôn ngữ toàn cầu.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q28',
    question_number: 28,
    content: 'Giao thức truyền file bảo mật sử dụng đường truyền SSH có tên là gì?',
    option_a: 'TFTP',
    option_b: 'SFTP (SSH File Transfer Protocol)',
    option_c: 'FTP Plain',
    option_d: 'Telnet File',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'SFTP mã hóa cả kênh điều khiển lẫn dữ liệu truyền tải thông qua cổng 22.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q29',
    question_number: 29,
    content: 'Trong cấu trúc dữ liệu cây nhị phân tìm kiếm (BST), phần tử ở cây con bên trái (Left Subtree) luôn có giá trị như thế nào so với nút gốc (Root)?',
    option_a: 'Luôn lớn hơn nút gốc',
    option_b: 'Luôn nhỏ hơn nút gốc',
    option_c: 'Bằng nút gốc',
    option_d: 'Ngẫu nhiên',
    correct_answer: 'B',
    points: 0.6,
    category: 'Cấu trúc dữ liệu',
    explanation: 'Quy tắc BST: Cây con trái < Nút gốc < Cây con phải.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q30',
    question_number: 30,
    content: 'Mô hình điện toán phân tán bất biến sử dụng các khối liên kết bằng mã băm mật mã (cryptographic hash) là gì?',
    option_a: 'Blockchain',
    option_b: 'Grid Computing',
    option_c: 'Serverless Function',
    option_d: 'Microservices',
    correct_answer: 'A',
    points: 0.6,
    category: 'Công nghệ mới',
    explanation: 'Blockchain là chuỗi các khối dữ liệu liên kết an toàn bằng mã băm mật mã học.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q31',
    question_number: 31,
    content: 'Trong hệ điều hành, thành phần cốt lõi quản lý CPU, bộ nhớ và thiết bị ngoại vi được gọi là gì?',
    option_a: 'Shell',
    option_b: 'Kernel (Nhân hệ điều hành)',
    option_c: 'Compiler',
    option_d: 'Desktop Environment',
    correct_answer: 'B',
    points: 0.6,
    category: 'Hệ điều hành',
    explanation: 'Kernel là cầu nối trung gian cốt lõi giữa phần cứng máy tính và các ứng dụng phần mềm.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q32',
    question_number: 32,
    content: 'Địa chỉ MAC (Media Access Control) có độ dài bao nhiêu bit?',
    option_a: '32 bit',
    option_b: '48 bit',
    option_c: '64 bit',
    option_d: '128 bit',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Địa chỉ MAC gồm 48 bit (6 byte), thường viết dưới dạng Hexadecimal (ví dụ: 00:1A:2B:3C:4D:5E).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q33',
    question_number: 33,
    content: 'Trong mô hình quan hệ cơ sở dữ liệu (RDBMS), tính chất ACID viết tắt của các từ nào?',
    option_a: 'Atomicity, Consistency, Isolation, Durability',
    option_b: 'Access, Control, Identity, Data',
    option_c: 'Array, Class, Integer, Decimal',
    option_d: 'Asynchronous, Connected, Indexed, Distributed',
    correct_answer: 'A',
    points: 0.6,
    category: 'Cơ sở dữ liệu',
    explanation: 'ACID đảm bảo tính toàn vẹn giao dịch: Tính nguyên tố, Tính nhất quán, Tính cô lập, Tính bền vững.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q34',
    question_number: 34,
    content: 'Kỹ thuật xác thực 2 yếu tố (2FA / MFA) kết hợp ít nhất hai trong số các yếu tố nào?',
    option_a: 'Hai mật khẩu khác nhau',
    option_b: 'Điều bạn biết (Mật khẩu), Điều bạn có (Thiết bị/OTP), Điều bạn là (Sinh trắc học)',
    option_c: 'Hai địa chỉ email',
    option_d: 'Tên người dùng và số điện thoại',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'MFA yêu cầu xác thực kết hợp giữa tri thức (Knowledge), sở hữu (Possession) hoặc sinh trắc (Inherence).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q35',
    question_number: 35,
    content: 'Trong giao thức HTTP, mã trạng thái (Status Code) 404 có ý nghĩa là gì?',
    option_a: 'Yêu cầu thành công (OK)',
    option_b: 'Không tìm thấy tài nguyên yêu cầu (Not Found)',
    option_c: 'Lỗi máy chủ nội bộ (Internal Server Error)',
    option_d: 'Không có quyền truy cập (Forbidden)',
    correct_answer: 'B',
    points: 0.6,
    category: 'Công nghệ thông tin',
    explanation: 'HTTP 404 Not Found báo hiệu máy chủ không tìm thấy tài nguyên tại URI được chỉ định.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q36',
    question_number: 36,
    content: 'Công nghệ WebSocket cung cấp kiểu giao tiếp nào giữa client và server?',
    option_a: 'Giao tiếp một chiều (Half-Duplex) theo chu kỳ',
    option_b: 'Kênh truyền song công toàn phần hai chiều (Full-Duplex) liên tục qua 1 kết nối TCP duy nhất',
    option_c: 'Chỉ gửi dữ liệu từ server tới client',
    option_d: 'Chỉ dùng cho gửi file lớn',
    correct_answer: 'B',
    points: 0.6,
    category: 'Lập trình mạng',
    explanation: 'WebSocket mở kênh giao tiếp 2 chiều toàn phần (Full-Duplex) độ trễ cực thấp trong thời gian thực.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q37',
    question_number: 37,
    content: 'Phương pháp kiểm thử phần mềm mà người kiểm thử không cần biết cấu trúc mã nguồn bên trong được gọi là gì?',
    option_a: 'White Box Testing (Hộp trắng)',
    option_b: 'Black Box Testing (Hộp đen)',
    option_c: 'Gray Box Testing',
    option_d: 'Unit Testing',
    correct_answer: 'B',
    points: 0.6,
    category: 'Kỹ thuật phần mềm',
    explanation: 'Black Box Testing kiểm tra chức năng hệ thống thuần túy dựa trên đầu vào và đầu ra mà không soi mã nguồn.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q38',
    question_number: 38,
    content: 'Trong toán học rời rạc và mạng máy tính, thuật toán Dijkstra được dùng để giải quyết bài toán gì?',
    option_a: 'Tìm đường đi ngắn nhất từ một đỉnh nguồn đến tất cả các đỉnh trong đồ thị có trọng số không âm',
    option_b: 'Sắp xếp dãy số',
    option_c: 'Tìm cây khung nhỏ nhất (MST)',
    option_d: 'Kiểm tra tính liên thông của đồ thị',
    correct_answer: 'A',
    points: 0.6,
    category: 'Thuật toán',
    explanation: 'Thuật toán Dijkstra tìm đường đi ngắn nhất được ứng dụng cốt lõi trong định tuyến mạng (OSPF).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q39',
    question_number: 39,
    content: 'Khái niệm "Zero Day Vulnerability" (Lỗ hổng Zero-day) trong an ninh mạng dùng để chỉ cái gì?',
    option_a: 'Lỗ hổng đã được vá cách đây 0 ngày',
    option_b: 'Lỗ hổng phần mềm chưa từng được nhà phát hành biết đến hoặc chưa có bản vá chính thức',
    option_c: 'Virus không gây hại',
    option_d: 'Tường lửa bị tắt tạm thời',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'Zero-day là lỗ hổng an ninh chưa được công bố và chưa có bản vá, có nguy cơ bị khai thác cao nhất.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q40',
    question_number: 40,
    content: 'Trong hệ thống mạng LAN, thiết bị nào hoạt động ở tầng 2 (Data Link Layer) và chuyển tiếp khung (Frame) dựa trên địa chỉ MAC?',
    option_a: 'Router',
    option_b: 'Switch (Bộ chuyển mạch)',
    option_c: 'Hub',
    option_d: 'Repeater',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Switch Layer 2 duy trì bảng CAM để chuyển tiếp các gói tin dựa vào địa chỉ MAC đích.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q41',
    question_number: 41,
    content: 'Trong quản trị mạng, giao thức DHCP (Dynamic Host Configuration Protocol) có chức năng chính là gì?',
    option_a: 'Chặn virus mạng',
    option_b: 'Tự động cấp phát địa chỉ IP và cấu hình mạng cho các thiết bị kết nối',
    option_c: 'Đồng bộ thời gian hệ thống',
    option_d: 'Mã hóa email',
    correct_answer: 'B',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'DHCP tự động phân phối địa chỉ IP, Subnet mask, Default Gateway và DNS cho các client.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q42',
    question_number: 42,
    content: 'Công nghệ RAID 1 (Redundant Array of Independent Disks) sử dụng cơ chế nào để bảo vệ dữ liệu?',
    option_a: 'Striping (Phân mảnh không sao lưu)',
    option_b: 'Mirroring (Sao chép gương dữ liệu giống nhau lên 2 ổ đĩa)',
    option_c: 'Parity phân tán',
    option_d: 'Nén dữ liệu',
    correct_answer: 'B',
    points: 0.6,
    category: 'Hệ thống máy chủ',
    explanation: 'RAID 1 ghi dữ liệu song song vào 2 ổ đĩa giống hệt nhau, hỏng 1 ổ hệ thống vẫn chạy bình thường.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q43',
    question_number: 43,
    content: 'Trong lập trình TypeScript / JavaScript, từ khóa `const` dùng để khai báo biến có đặc tính gì?',
    option_a: 'Biến có thể gán lại giá trị bất kỳ lúc nào',
    option_b: 'Biến có phạm vi khối (block-scoped) và không thể gán lại giá trị mới sau khi khởi tạo',
    option_c: 'Biến toàn cục có thể xóa',
    option_d: 'Biến luôn có kiểu chuỗi',
    correct_answer: 'B',
    points: 0.6,
    category: 'Lập trình',
    explanation: '`const` tạo hằng số có block scope và không thể reassign.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q44',
    question_number: 44,
    content: 'Mạng riêng ảo VPN (Virtual Private Network) tạo ra điều gì để đảm bảo dữ liệu truyền qua Internet công cộng được an toàn?',
    option_a: 'Đường truyền cáp quang riêng biệt',
    option_b: 'Một đường hầm mã hóa an toàn (Encrypted Tunnel)',
    option_c: 'Tăng tốc độ băng thông gấp đôi',
    option_d: 'Xóa toàn bộ cookie duyệt web',
    correct_answer: 'B',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'VPN thiết lập một đường hầm mã hóa (IPSec, OpenVPN, WireGuard) bảo vệ lưu lượng dữ liệu.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q45',
    question_number: 45,
    content: 'Khái niệm "Big Data" (Dữ liệu lớn) thường được định nghĩa bằng các đặc trưng 5V, trong đó "Velocity" có nghĩa là gì?',
    option_a: 'Khối lượng dữ liệu khổng lồ',
    option_b: 'Tốc độ sinh ra và xử lý dữ liệu nhanh theo thời gian thực',
    option_c: 'Sự đa dạng về định dạng dữ liệu',
    option_d: 'Giá trị thương mại của dữ liệu',
    correct_answer: 'B',
    points: 0.6,
    category: 'Khoa học dữ liệu',
    explanation: 'Velocity phản ánh tốc độ luân chuyển và xử lý cực nhanh của luồng dữ liệu lớn.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q46',
    question_number: 46,
    content: 'Bộ nhớ RAM (Random Access Memory) thuộc loại bộ nhớ nào?',
    option_a: 'Non-volatile memory (Không mất dữ liệu khi mất điện)',
    option_b: 'Volatile memory (Mất toàn bộ dữ liệu khi ngắt nguồn điện)',
    option_c: 'Bộ nhớ quang học ghi đĩa',
    option_d: 'Bộ nhớ từ tính băng từ',
    correct_answer: 'B',
    points: 0.6,
    category: 'Kiến trúc máy tính',
    explanation: 'RAM là bộ nhớ khả biến (Volatile), dữ liệu lưu trữ sẽ bị xóa sạch khi máy tính tắt nguồn.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q47',
    question_number: 47,
    content: 'Phương thức HTTP nào được thiết kế để gửi dữ liệu từ client lên server nhằm tạo mới một tài nguyên (Resource)?',
    option_a: 'GET',
    option_b: 'POST',
    option_c: 'DELETE',
    option_d: 'HEAD',
    correct_answer: 'B',
    points: 0.6,
    category: 'Lập trình web',
    explanation: 'HTTP POST được dùng để gửi dữ liệu lên máy chủ để xử lý hoặc tạo mới bản ghi.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q48',
    question_number: 48,
    content: 'Hình thức tấn công phi kỹ thuật (Social Engineering) giả mạo tổ chức uy tín qua email/tin nhắn để đánh cắp mật khẩu gọi là gì?',
    option_a: 'Phishing (Lừa đảo mạo danh)',
    option_b: 'Ransomware (Mã độc tống tiền)',
    option_c: 'Rootkit',
    option_d: 'Spyware (Phần mềm gián điệp)',
    correct_answer: 'A',
    points: 0.6,
    category: 'An toàn thông tin',
    explanation: 'Phishing khai thác yếu tố tâm lý con người để chiếm đoạt thông tin đăng nhập và tài khoản.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q49',
    question_number: 49,
    content: 'Trong hệ quản trị cơ sở dữ liệu, một Khóa chính (Primary Key) phải thỏa mãn điều kiện bắt buộc nào?',
    option_a: 'Phải chứa giá trị NULL',
    option_b: 'Các giá trị phải là duy nhất (Unique) và không được chứa giá trị NULL (Not Null)',
    option_c: 'Chỉ được có kiểu dữ liệu là ngày tháng',
    option_d: 'Phải trùng lặp trên tất cả các dòng',
    correct_answer: 'B',
    points: 0.6,
    category: 'Cơ sở dữ liệu',
    explanation: 'Khóa chính xác định duy nhất từng bản ghi trong bảng, bắt buộc Unique và Not Null.',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
  {
    id: 'Q50',
    question_number: 50,
    content: 'Trong mạng máy tính, lệnh `ping` sử dụng giao thức nào để kiểm tra khả năng tiếp cận và độ trễ tới một địa chỉ đích?',
    option_a: 'ICMP (Internet Control Message Protocol)',
    option_b: 'IGMP',
    option_c: 'BGP',
    option_d: 'OSPF',
    correct_answer: 'A',
    points: 0.6,
    category: 'Mạng máy tính',
    explanation: 'Lệnh ping gửi các gói tin ICMP Echo Request và nhận lại ICMP Echo Reply để đo độ trễ mạng (RTT).',
    question_type: 'MULTIPLE_CHOICE',
    created_at: new Date().toISOString(),
  },
];
